config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index', as: :home
  get '/about' => 'home#about'

  resources :posts do
    resources :comments
  end

  resources :users, only: [:new, :create, :edit, :update]
  resources :password_resets, only: [:new, :edit, :update]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :description, presence: true
end

app/models/password_reset.rb
class PasswordReset < ApplicationRecord
  has_secure_password
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates_length_of :title, minimum: 7

  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user
    redirect_to new_session_path, alert: 'please sign in' unless user_signed_in?
  end

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if user_signed_in?
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    comment_params = params.require(:comment).permit([:title, :description])
    @comment = Comment.new comment_params
    @post = Post.find params[:post_id]
    @comment.post = @post
    if @comment.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @comment = Comment.find params[:id]
  end

  def index
    @comments = Comment.order(created_at: :desc)
  end

  def destroy
    @comment = Comment.find params[:id]
    @comment.destroy
    redirect_to post_comments_path
  end

  def edit
    @comment = Comment.find params[:id]
  end

  def update
    @comment = Comment.find params[:id]
    comment_params = params.require(:comment).permit(:title, :description)

    if @comment.update comment_params
      redirect_to post_comment_path(@comment)
    else
      render :edit
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(updated_at: :desc).limit(5)
  end

  def about
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
    @password = PasswordReset.new
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    password_params = params.require(:passwordreset).permit(:password, :password_confirmation)

    if @user.update password_params
      redirect_to home_path
    else
      render :edit
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    post_params = params.require(:post).permit([:title, :description])
    @post = Post.new post_params

    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find params[:id]
    @comment = Comment.new
  end

  def index
    @posts = Post.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    post_params = params.require(:post).permit(:title, :description)

    if @post.update post_params
      redirect_to post_path(@post)
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by_email params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_path, notice: 'Signed In'
    else
      flash.now[:alert] = 'Wrong credentials'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path, notice: 'Signed Out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit([:first_name,
                                                :last_name,
                                                :email,
                                                :password,
                                                :password_confirmation])

    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to home_path, notice: 'Thanks for registering'
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find params[:id]
    user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)

    if @user.update user_params
      redirect_to home_path
    else
      render :edit
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= @comment.errors.full_messages.join(', ') %>

<%= form_for @comment do |c| %>
  <div>
    <%= c.label :title %>
    <%= c.text_field :title %>
  </div>

  <div>
    <%= c.label :description %>
    <%= c.text_field :description %>
  </div>

  <%= c.submit %>
<% end %>

app/views/comments/index.html.erb
<h1>All Comments</h1>

<%= link_to 'New comment', new_post_comment_path %>
<hr>

<% @comments.each do |p| %>
  <%= link_to p.title, post_path(p) %>
  <hr>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= @comment.errors.full_messages.join(', ') %>

<%= form_for @comment, :url => post_comments_path do |c| %>
  <div>
    <%= c.label :title %>
    <%= c.text_field :title %>
  </div>

  <div>
    <%= c.label :description %>
    <%= c.text_field :description %>
  </div>

  <%= c.submit %>
<% end %>

app/views/comments/show.html.erb
<h1><%= @comment.title %></h1>
<p><%= @comment.description %></p>

<%= link_to 'edit', edit_post_comment_path(@comment) %>
<%= link_to 'delete', post_comment_path(@comment),
                      method: :delete,
                      data: { confirm: 'Are you sure you want to delete this comment?' } %>

app/views/home/about.html.erb
<h1>About me</h1>
<%= image_tag('me.jpg', height: '100') %>

app/views/home/index.html.erb
<h1>Welcome to my blog</h1>
<h3>Here is the trending blog posts:</h3>

<div id="trending_posts">
  <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Updated Time</th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |p| %>
          <tr>
            <td><%= link_to p.title, post_path(p) %></td>
            <td><%= truncate(p.description, length: 10) %></td>
            <td><%= p.updated_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id='contents'>

      <div id="header">
        <div class="jumbotron">
          <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
              <div class="navbar-header">
                <a class="navbar-brand">Dan's Awesome Blog</a>
              </div>
              <ul class="nav navbar-nav">
                <li><%= link_to 'Home', home_path %></li>
                <li><%= link_to 'About', about_path %></li>
                <li><%= link_to 'Posts', posts_path %></li>
                <li><%= link_to 'New Post', new_post_path %></li>
                <% if user_signed_in? %>
                  <li>
                    <p class="navbar-text">Hello <%= current_user.first_name %></p>
                  </li>
                  <li><%= button_to 'Change Password', edit_password_reset_path(current_user), method: :get, class:"btn btn-default navbar-btn" %></li>
                  <li><%= button_to 'Edit Profile', edit_user_path(current_user), method: :get, class:"btn btn-default navbar-btn" %></li>
                  <li><%= button_to 'Sign Out', sessions_path, method: :delete, class:"btn btn-default navbar-btn" %></li>
                <% else %>
                  <li><%= link_to 'Sign In', new_session_path %></li>
                  <li><%= link_to 'Sign Up', new_user_path %></li>
                <% end %>
              </ul>
            </div>
          </nav>
        </div>
      </div>

      <!-- <nav>
        <%= link_to 'Home', home_path %>
        |
        <%= link_to 'About', about_path %>
        |
        <%= link_to 'Posts', posts_path %>
        |
        <%= link_to 'New Post', new_post_path %>
      </nav> -->
      <%= yield %>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Edit Password</h1>

<%= form_for @user, url: password_reset_path(@user), html:{method: :path} do |f| %>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= @post.errors.full_messages.join(', ') %>

<%= form_for @post do |p| %>
  <div>
    <%= p.label :title %>
    <%= p.text_field :title %>
  </div>

  <div>
    <%= p.label :description %>
    <%= p.text_field :description %>
  </div>

  <%= p.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Updated Time</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |p| %>
      <tr>
        <td><%= link_to p.title, post_path(p) %></td>
        <td><%= truncate(p.description, length: 10) %></td>
        <td><%= p.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= will_paginate @posts %></p>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= @post.errors.full_messages.join(', ') %>

<%= form_for @post do |p| %>
  <div>
    <%= p.label :title %>
    <%= p.text_field :title %>
  </div>

  <div>
    <%= p.label :description %>
    <%= p.text_field :description %>
  </div>

  <%= p.submit %>
<% end %>

app/views/posts/show.html.erb
<div id="post_div">
<h2><%= @post.title %></h2>
<p><%= @post.description %></p>

<%= link_to 'edit', edit_post_path(@post) %>
<%= link_to 'delete', post_path(@post),
                      method: :delete,
                      data: { confirm: 'Are you sure you want to delete this post?' } %>

<hr>
<h3>New Comment</h3>
<%= @comment.errors.full_messages.join(', ') %>
<%= form_for [@post, @comment] do |f| %>
  <div>
    <div class="left">
      <%= f.label :title %>
    </div>

    <div class="right">
      <%= f.text_field :title %>
    </div>
  </div>

  <br>
  <br>

  <div>
    <div class="left">
      <%= f.label :description %>
    </div>

    <div class="right">
      <%= f.text_area :description %>
    </div>
  </div>

  <br>
  <br>

  <%= f.submit %>
<% end %>
<hr>
</div>

<div id="comment_div">
  <h3>All comments</h3>

  <table class="table table-striped">
      <thead>
        <tr>
          <th>Author</th>
          <th>Description</th>
          <th>Created Time</th>
        </tr>
      </thead>

      <tbody>
        <% @post.comments.order(created_at: :desc).each do |comment| %>
          <tr>
            <td><%= 'Author name' %></td>
            <td><%= comment.description %></td>
            <td><%= comment.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/users/edit.html.erb
<h1>Edit Page</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit 'Register' %>
  </div>
<% end %>